#!/usr/bin/env python3
"""
NeuroCardiac Shield — AI Mentions Check
========================================
Scans the repository for any mentions of AI assistants or tools.
Returns exit code 1 if any banned terms are found.

Usage:
    python tools/no_ai_mentions_check.py

Authors: Mohd Sarfaraz Faiyaz, Vaibhav D. Chandgir
NYU Tandon School of Engineering | ECE-GY 9953 | Fall 2025
"""

import os
import re
import sys
from pathlib import Path
from typing import List, Tuple

# Banned terms (case-insensitive)
BANNED_TERMS = [
    r'\bclaude\b',
    r'\banthropic\b',
    r'\bopenai\b',
    r'\bchatgpt\b',
    r'\bgpt-4\b',
    r'\bgpt-3\b',
    r'\bgpt4\b',
    r'\bgpt3\b',
    r'\bllm\b',
    r'\blarge language model\b',
    r'\bai assistant\b',
    r'\bai-generated\b',
    r'\bgenerated by ai\b',
    r'\bco-authored-by:.*anthropic\b',
    r'\bco-authored-by:.*openai\b',
    r'\bnoreply@anthropic\b',
    r'\bgemini\b',
    r'\bcopilot\b',
    r'\bgithub copilot\b',
]

# File extensions to scan
SCAN_EXTENSIONS = {
    '.py', '.md', '.txt', '.rst', '.html', '.htm', '.css', '.js', '.ts',
    '.jsx', '.tsx', '.json', '.yaml', '.yml', '.toml', '.cfg', '.ini',
    '.c', '.h', '.cpp', '.hpp', '.sh', '.bash', '.zsh', '.fish',
    '.dockerfile', '.gitignore', '.env.example'
}

# Directories to skip
SKIP_DIRS = {
    '.git', 'node_modules', 'venv', 'env', '.venv', '__pycache__',
    '.claude', '.cursor', 'dist', 'build', '.next', '.cache',
    'coverage', '.pytest_cache', '.mypy_cache', 'htmlcov'
}

# Files to skip
SKIP_FILES = {
    'no_ai_mentions_check.py',  # This file itself
    'package-lock.json',
    'yarn.lock',
    'pnpm-lock.yaml'
}


def get_repo_root() -> Path:
    """Get the repository root directory."""
    script_dir = Path(__file__).parent
    return script_dir.parent


def should_scan_file(file_path: Path) -> bool:
    """Check if a file should be scanned."""
    # Check extension
    if file_path.suffix.lower() not in SCAN_EXTENSIONS:
        # Also check files without extension (like Dockerfile, Makefile)
        if file_path.name not in {'Dockerfile', 'Makefile', 'README', 'LICENSE'}:
            return False

    # Check if in skip list
    if file_path.name in SKIP_FILES:
        return False

    return True


def should_skip_dir(dir_name: str) -> bool:
    """Check if a directory should be skipped."""
    return dir_name in SKIP_DIRS


def scan_file(file_path: Path) -> List[Tuple[int, str, str]]:
    """
    Scan a file for banned terms.

    Returns:
        List of tuples: (line_number, matched_term, line_content)
    """
    violations = []

    try:
        with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
            for line_num, line in enumerate(f, 1):
                for pattern in BANNED_TERMS:
                    if re.search(pattern, line, re.IGNORECASE):
                        match = re.search(pattern, line, re.IGNORECASE)
                        violations.append((line_num, match.group(), line.strip()[:100]))
    except Exception as e:
        print(f"  Warning: Could not read {file_path}: {e}", file=sys.stderr)

    return violations


def main() -> int:
    """Main entry point."""
    print("=" * 60)
    print("  NeuroCardiac Shield — AI Mentions Check")
    print("=" * 60)
    print()

    repo_root = get_repo_root()
    print(f"Scanning: {repo_root}")
    print()

    total_files = 0
    total_violations = 0
    violation_files = []

    for root, dirs, files in os.walk(repo_root):
        # Remove skip directories from dirs to prevent descending into them
        dirs[:] = [d for d in dirs if not should_skip_dir(d)]

        for file_name in files:
            file_path = Path(root) / file_name

            if not should_scan_file(file_path):
                continue

            total_files += 1
            violations = scan_file(file_path)

            if violations:
                total_violations += len(violations)
                rel_path = file_path.relative_to(repo_root)
                violation_files.append((rel_path, violations))

    # Report results
    print(f"Files scanned: {total_files}")
    print()

    if violation_files:
        print("=" * 60)
        print("  VIOLATIONS FOUND")
        print("=" * 60)
        print()

        for rel_path, violations in violation_files:
            print(f"  File: {rel_path}")
            for line_num, term, content in violations:
                print(f"    Line {line_num}: Found '{term}'")
                print(f"      → {content}")
            print()

        print("=" * 60)
        print(f"  FAILED: {total_violations} violation(s) in {len(violation_files)} file(s)")
        print("=" * 60)
        return 1
    else:
        print("=" * 60)
        print("  PASSED: No AI mentions found")
        print("=" * 60)
        return 0


if __name__ == '__main__':
    sys.exit(main())
